# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-19 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SectorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('RegionName', models.CharField(max_length=40)),
                ('Startdate', models.DateTimeField(blank=True)),
                ('Enddate', models.DateTimeField(blank=True)),
                ('Resultdate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
