# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-19 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectordetail',
            name='Resultdate',
            field=models.DateTimeField(blank=True),
        ),
    ]
