# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-18 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('Party_Name', models.CharField(max_length=40)),
                ('RegionName', models.CharField(default='', max_length=40)),
                ('StateName', models.CharField(default='', max_length=40)),
                ('UniqueKey', models.CharField(max_length=3)),
                ('VoterCounter', models.IntegerField(default=0)),
                ('Logo', models.FileField(default='', max_length=1000, upload_to=b'')),
            ],
        ),
    ]
