# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-21 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SectorParties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='CandidateName',
            field=models.CharField(default='', max_length=40),
        ),
    ]
