# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-21 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Profile', models.FileField(max_length=1000, upload_to=b'')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=5)),
                ('Party_Name', models.CharField(max_length=40)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
