# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-21 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='sex',
            field=models.CharField(max_length=6),
        ),
    ]
