# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoterDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('VoterID', models.CharField(max_length=10)),
                ('Age', models.IntegerField(max_length=10)),
                ('Sex', models.CharField(max_length=5)),
                ('pin', models.IntegerField(max_length=6)),
                ('mobile_number', models.CharField(default='', max_length=10)),
                ('regionOfVoting', models.CharField(max_length=30)),
            ],
        ),
    ]
