# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-17 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoterData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voterdatabase',
            name='pin',
        ),
    ]
