# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-17 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoterData', '0002_remove_voterdatabase_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='voterdatabase',
            name='pin',
            field=models.IntegerField(default=2, max_length=6),
            preserve_default=False,
        ),
    ]
