# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoterData', '0003_voterdatabase_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voterdatabase',
            name='pin',
            field=models.IntegerField(default='', max_length=6),
        ),
    ]
